### ISSUE TITLE
ALP Support

### ISSUE THREAD

**Issue by vilbht** [adamsmt/amplify#1]
hi Adam,

AFAIK this is one of the only AMP focused plugins for Craft. Just new to development, would love to help. FYI , they launched ALP today which uses a different JS file to boost landing pages that are linked to ads:

https://github.com/jasti/amp-ads-testing/blob/master/dfp-amp-testing/amp_tests/playground/landingpages/ALP%20Docs/alp.md

**Comment by adamsmt** [comment]
Hello Vilav,

I just started this project out of a necessity for amp on a craft project after realizing there was an opportunity in the craft AMP space for a simple plugin. I'm happy to take a look at any pull requests and suggestions that you might have on improvement.

Thanks!

Matt
